config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
    post 'users/verify_otp', to: 'users/sessions#check_otp'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :quotes do
    resource :line_item_dates, except: [:index, :show]
  end

  resources :two_factor_auth do
    collection do
      get :show
      post :enable
      post :disable
    end
  end



  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/line_item_date.rb
class LineItemDate < ApplicationRecord
  belongs_to :quote

  validates :date, presence: true, uniqueness: { scope: :quote_id }

  scope :ordered, -> { order(date: :asc) }
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :line_item_dates, dependent: :destroy

  belongs_to :company

  validates :name, presence: true

  scope :ordered, -> {order(id: :desc)}

  # after_create_commit -> { broadcast_prepend_later_to "quotes" }
  # after_update_commit -> { broadcast_replace_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }
  # Those three callbacks are equivalent to the following single line
  broadcasts_to ->(quote) { [quote.company, "quotes"] }, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable

  belongs_to :company

  # generate and save new otp secret if doesnt already exist
  def generate_otp_secret
    self.otp_secret ||= ROTP::Base32.random_base32
    save!
  end

  # generates the qrcode url to be scanned by authenticator app
  def otp_provisioning_uri
    issuer = 'MyApp'
    label = "#{issuer}:#{self.email}"
    ROTP::TOTP.new(self.otp_secret, isseur: issuer).provisioning_uri(label)
  end

  def generate_qr_code
    qr_code = RQRCode::QRCode.new(self.otp_provisioning_uri)
    qr_code.as_svg(module_size: 6)
  end

  def validate_and_consume_otp!(otp_attempt)
    totp = ROTP::TOTP.new(self.otp_secret);
    totp.verify(otp_attempt, drift_behind: 30)
  end

  def name
    email.split("@").first.capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action -> {sleep 3}
  before_action :authenticate_user!, unless: :devise_controller?

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end

  helper_method :current_company

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = current_company.quotes.ordered
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy

    respond_to do |format|
    format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
    format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end

end

app/controllers/two_factor_auth_controller.rb
class TwoFactorAuthController < ApplicationController
  before_action :authenticate_user!

  # display the qr and form for enabling 2fa
  def show
    current_user.generate_otp_secret if current_user.otp_secret.nil?
  end

  # enable 2fa
  def enable
    if current_user.validate_and_consume_otp!(params[:otp_attempt])
      current_user.update(otp_enabled: true)
      redirect_to root_path, notice: 'Two factor authentication enabled successfully'
    else
      flash[:alert] = 'Invalid OTP code, please try again'
      render :show
    end
  end

  # disable 2fa
  def disable
    if current_user.validate_and_consume_otp!(params[:otp_attempt])
      current_user.update(otp_enabled: false, otp_secret: nil)
      redirect_to root_path, notice: 'Two factor authentication disabled successfully'
    else
      flash[:alert] = 'Invalid OTP code, please try again'
      render :show
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # Override the create method to enforce OTP check
  def create
    user = User.find_by(email: params[:user][:email])

    # Authenticate user with password first
    if user && user.valid_password?(params[:user][:password])
      # Check if OTP is enabled
      if user.otp_enabled?
        session[:user_id] = user.id
        redirect_to verify_otp_path and return
      else
        # If OTP is not enabled, sign them in directly
        sign_in user
        redirect_to root_path, notice: 'Logged in successfully'
      end
    else
      # Handle invalid login credentials
      flash[:alert] = 'Invalid email or password'
      render :new
    end
  end

  # OTP verification page
  def verify_otp
    if session[:user_id].nil?
      redirect_to new_user_session_path
    end
  end

  # Check OTP and sign in the user if valid
  def check_otp
    user = User.find(session[:user_id])
    if user.validate_and_consume_otp!(params[:otp_attempt])
      session[:otp_verified] = true
      sign_in(user)
      session.delete(:user_id) # Clean up session
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash[:alert] = 'Invalid OTP code, please try again.'
      render :verify_otp
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/two_factor_auth_helper.rb
module TwoFactorAuthHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div 
		class="flash__message"
		data-controller="removals"
		data-action="animationend->removals#remove"
	>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar__brand">
      <%= current_company.name %>
    </div>
    <div class="navbar__name">
      <%= current_user.name %>
    </div>
    <%= button_to "Sign Out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "btn btn--dark" %>
    <%= link_to "2FA",
                  two_factor_auth_index_path,
                  class: "btn btn--dark" %>

  <% else %>
    <%= link_to "Sign In",
                new_user_session_path,
                class: "btn btn--dark navbar__right"%>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
		<%= render "layouts/navbar"%>

		<div id="flash" class="flash">
			<%= render "layouts/flash" %>
		</div>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<main class="container">
	<h1>Quote Editor</h1>
	<p>A blazing fast quote editor built with Hotwire</p>

	<% if user_signed_in? %>
		<%= link_to "View Quotes", quotes_path, class: "btn btn--dark" %>
	<% else %>
		<%= link_to "View Quotes", quotes_path, class: "btn btn--dark" %>
	<% end %>
</main>

app/views/quotes/_empty_state.html.erb
<div class="empty-state">
	<p class="empty-state__text">
		You don't have any quotes yet!
	</p>

	<%= link_to "Add quote", new_quote_path, class: "btn btn--primary" %>
</div>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: {class: "quote form"} do |f| %>
	<% if quote.errors.any? %>
		<div class="error-message">
			<%= quote.errors.full_messages.to_sentence.capitalize%>
		</div>
		<% end %>
		<%= f.input :name, input_html: {autofocus: true} %>
		<%= link_to "Cancel", quotes_path, class: "btn btn--light"%>
		<%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do%>
	<div class="quote">
		<%= link_to quote.name, quote_path(quote), data: {turbo_frame: "_top"} %>
		<div class="quote__actions">
			<%= button_to "Delete", quote_path(quote), method: :delete, class: "btn btn--light" %>
			<%= link_to "Edit", edit_quote_path(quote), class: "btn btn--light" %>
		</div>
	</div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>
<%= render_turbo_stream_flash_messages %>

<% unless current_company.quotes.exists? %>
	<% turbo_stream.update Quote.new do %>
		<%= render "quotes/empty_state" %>
	<% end %>
<% end %>

app/views/quotes/edit.html.erb
<main class="container">
	<%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
	<div class="header">
		<h1>Edit Quote</h1>
	</div>
	<%= turbo_frame_tag @quote do %>
		<%= render "form", quote: @quote %>
	<% end %>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from current_company, "quotes" %>
<main class="container">
	<div class="header">
		<h1>Quotes</h1>
		<%= link_to "New quote", new_quote_path, data: {turbo_frame: dom_id(Quote.new)}, class: "btn btn--primary"%>
	</div>

	<%= turbo_frame_tag Quote.new do %>
		<%if @quotes.none? %>
			<% render "quotes/empty_state" %>
		<% end %>
	<% end %>
	
	<%= turbo_frame_tag "quotes" do %>
		<%= render @quotes %>
	<% end %>
</main>

app/views/quotes/new.html.erb
<main class="container">
	<%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
	<div class="header">
		<h1>New Quote</h1>
	</div>
	<%= turbo_frame_tag Quote.new do %>
		<%= render "form", quote: @quote %>
	<% end %>
</main>

app/views/quotes/show.html.erb
<main class="container">
	<%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
	
	<div class="header">
		<h1><%= @quote.name %></h1>
	</div>

	<%= link_to "New Date", new_quote_line_item_date_path(@quote), class: "btn btn--primary" %>
</main>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>

app/views/two_factor_auth/show.html.erb
<h2>Two-Factor Authentication Setup</h2>

<% if current_user.otp_enabled %>
  <p>Two-factor authentication is <strong>enabled</strong>.</p>

  <%= form_tag disable_two_factor_auth_index_path do %>
    <label for="otp_attempt">Enter your OTP code to disable 2FA:</label>
    <%= text_field_tag :otp_attempt %>
    <%= submit_tag 'Disable 2FA' %>
  <% end %>

<% else %>
  <p>Scan the QR code below with your authenticator app (Google Authenticator, Authy, etc.).</p>

  <!-- Display the QR code generated by rqrcode -->
  <div>
    <%= raw current_user.generate_qr_code %>
  </div>

  <%= form_tag enable_two_factor_auth_index_path do %>
    <label for="otp_attempt">Enter your OTP code:</label>
    <%= text_field_tag :otp_attempt %>
    <%= submit_tag 'Enable 2FA' %>
  <% end %>
<% end %>